name: cat_trivia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  intl: any
  json_serializable: ^6.7.1
  lottie: ^2.5.0
  path: ^1.8.3
  path_provider: ^2.0.15
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0' 
  hive_generator: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#F1F4F7"
  adaptive_icon_foreground: "assets/logo_fg.png"
  image_path_ios: "assets/logo_ios.png"

flutter_native_splash:
  color: "#F1F4F7"
  image: "assets/splash.png"
  fullscreen: true
  android_12:
    image:  "assets/splash.png"
    icon_background_color: "#F1F4F7"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
